### ISSUE TITLE
#Tags?

### ISSUE THREAD

**Issue by loup-brun** [loup-brun/desorde.loupbrun.ca#16]
who wants tags @Therealemilio ?

![tags](https://user-images.githubusercontent.com/9596476/55425086-a7f2df00-554f-11e9-81d5-83836446658b.jpeg)

**Comment by loup-brun** [comment]
Quel nom donner à cela?

Tags, c’est un peu le lieu commun par défaut (en anglais en plus) mais ça pourrait être :

- Collections
- Thèmes
- Étiquettes
- …

**Comment by Therealemilio** [comment]
-Armoires
-Classeurs
-Poignées
-Caisses

-» Catég

**Comment by loup-brun** [comment]
On veut `categ`

URL: `/categ/xyz`

**Comment by loup-brun** [comment]
## 1) Page des _categ_

C'est tu pas nice ça :

![categ](https://user-images.githubusercontent.com/9596476/55671390-8e0e1080-585d-11e9-8b53-ce7d6b5c3557.jpeg)

---

## 2) Page d'une collection

![term](https://user-images.githubusercontent.com/9596476/55671386-89e1f300-585d-11e9-9843-d4708252a58d.jpeg)

---
## 3) Page individuelle

Pis pour une page avec les métadonnées suivantes :

```yaml
---
title: momomo
date: 2018-05-01
author: Émile Brassard
categ:
- napomo
---
```

![napomo](https://user-images.githubusercontent.com/9596476/55671391-8fd7d400-585d-11e9-8a7d-a9eb118e37b6.jpeg)

**Comment by Therealemilio** [comment]
TROP COOL!
